apiVersion: v1
kind: Secret
metadata:
  name: petclinic-cnx
  namespace: spring-petclinic
type: Opaque
stringData:
    PC_MYSQL_CUSTOMERS: 'jdbc:mysql://{VIP DNS}:6446/mysql?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=customers-db'
    PC_MYSQL_VETS: 'jdbc:mysql://{VIP DNS}:6446/mysql?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=vets-db'
    PC_MYSQL_VISITS: 'jdbc:mysql://{VIP DNS}:6446/mysql?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=visits-db'
    PC_USERNAME: 'pds'
    PC_PASSWORD: '{pds password}'
